In [3]:
# https://www.youtube.com/watch?v=LF79PaCjeFU&list=PLTmQbi1PYZ_EnBmO1-E0Z81ArnE-zSR1a

#### Data Preprocessing tutorial ###

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

#### Load Dataset

In [10]:
dataset = pd.read_csv('C:\\Users\\Shardha Nand\\Desktop\\EmployData.csv')

##### create depedent and indepedent variable vetor

In [6]:
x = dataset.iloc[:,:-1].values
# [:,:-1]: The [:,:] part specifies that you want to select all rows and 
# all columns. The [:-1] part specifies that you want to select all columns
# except the last one.

In [7]:
print(x)

[['Mumbai' 3.0 51000.0]
 ['Newyork' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['Newyork' nan 66000.0]
 ['Tokyo' 48.0 nan]
 ['Tokyo' nan 51000.0]
 ['Singapore' 33.0 69000.0]
 ['Newyork' 105.0 79000.0]
 ['Newyork' 35.0 56000.0]
 ['Tokyo' nan 50000.0]]


In [8]:
y = dataset.iloc[:,-1].values
# [:,-1]:
# The -1 index for the columns indicates that you want to select the last 
# column 

In [9]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No']


##### handle missing values

In [10]:
print(dataset.isnull().sum())
print(dataset)

City                  0
Age                   3
Salary                1
Eligible for bonus    0
dtype: int64
        City    Age   Salary Eligible for bonus
0     Mumbai    3.0  51000.0                Yes
1    Newyork   27.0  48000.0                Yes
2     Mumbai   30.0  52000.0                 No
3    Newyork    NaN  66000.0                 No
4      Tokyo   48.0      NaN                Yes
5      Tokyo    NaN  51000.0                 No
6  Singapore   33.0  69000.0                 No
7    Newyork  105.0  79000.0                Yes
8    Newyork   35.0  56000.0                 No
9      Tokyo    NaN  50000.0                 No


In [11]:
# dataset.dropna(inplace=True)
# print(dataset)


In [12]:
print(dataset)

        City    Age   Salary Eligible for bonus
0     Mumbai    3.0  51000.0                Yes
1    Newyork   27.0  48000.0                Yes
2     Mumbai   30.0  52000.0                 No
3    Newyork    NaN  66000.0                 No
4      Tokyo   48.0      NaN                Yes
5      Tokyo    NaN  51000.0                 No
6  Singapore   33.0  69000.0                 No
7    Newyork  105.0  79000.0                Yes
8    Newyork   35.0  56000.0                 No
9      Tokyo    NaN  50000.0                 No


In [13]:
# print(dataset.describe())

In [14]:
from sklearn.impute import SimpleImputer

In [15]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
#imputer = SimpleImputer(missing_values=np.nan,strategy='median')
#imputer = SimpleImputer(missing_values=np.nan,strategy='mode')
#imputer = SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=10000)

In [16]:
imputer.fit(x[:,1:3])
# The code imputer.fit(x[:, 1:3]) is fitting the SimpleImputer to the data
# in columns 1 and 2 (the columns with indices 1 and 2) of the array x. 
# This means that the imputer will calculate the statistics 
# (e.g., mean, median, or most frequent value) for these specific columns 
# in order to impute missing values in those columns later.



SimpleImputer()

In [17]:
x[:,1:3]=imputer.transform(x[:,1:3])
# The code x[:, 1:3] = imputer.transform(x[:, 1:3]) is using the fitted 
# SimpleImputer to transform and replace the missing values in columns 1 
# and 2 of the array x with the imputed values.

print(x)


[['Mumbai' 3.0 51000.0]
 ['Newyork' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['Newyork' 40.142857142857146 66000.0]
 ['Tokyo' 48.0 58000.0]
 ['Tokyo' 40.142857142857146 51000.0]
 ['Singapore' 33.0 69000.0]
 ['Newyork' 105.0 79000.0]
 ['Newyork' 35.0 56000.0]
 ['Tokyo' 40.142857142857146 50000.0]]


In [18]:
# print(dataset.describe())

In [19]:
print(dataset.describe())
print(x[:,1:3])

              Age        Salary
count    7.000000      9.000000
mean    40.142857  58000.000000
std     31.625035  10770.329614
min      3.000000  48000.000000
25%     28.500000  51000.000000
50%     33.000000  52000.000000
75%     41.500000  66000.000000
max    105.000000  79000.000000
[[3.0 51000.0]
 [27.0 48000.0]
 [30.0 52000.0]
 [40.142857142857146 66000.0]
 [48.0 58000.0]
 [40.142857142857146 51000.0]
 [33.0 69000.0]
 [105.0 79000.0]
 [35.0 56000.0]
 [40.142857142857146 50000.0]]


##### Data encoding: handle/Encode Categorical data
# One Hot Encoding

In [20]:
from sklearn.compose import ColumnTransformer
# ColumnTransformer is a class provided by scikit-learn 
# (a popular machine learning library in Python) that 
# allows you to apply different transformations to 
# different columns or subsets of columns in your dataset

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")

In [23]:
print(ct)

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [0])])


In [24]:
x = np.array(ct.fit_transform(x))

In [25]:
print (x)

[[1.0 0.0 0.0 0.0 3.0 51000.0]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 30.0 52000.0]
 [0.0 1.0 0.0 0.0 40.142857142857146 66000.0]
 [0.0 0.0 0.0 1.0 48.0 58000.0]
 [0.0 0.0 0.0 1.0 40.142857142857146 51000.0]
 [0.0 0.0 1.0 0.0 33.0 69000.0]
 [0.0 1.0 0.0 0.0 105.0 79000.0]
 [0.0 1.0 0.0 0.0 35.0 56000.0]
 [0.0 0.0 0.0 1.0 40.142857142857146 50000.0]]


##### Label Encoding

In [26]:
from sklearn.preprocessing import LabelEncoder                

In [27]:
le = LabelEncoder()

In [28]:
y= le.fit_transform(y)

In [29]:
print(y)

[1 1 0 0 1 0 0 1 0 0]


##### split the dataset for training and testing

In [30]:
from sklearn.model_selection import train_test_split
# The train_test_split function from scikit-learn (sklearn) is a very 
# useful tool for splitting your dataset into training and testing 
# subsets. This is a common step in machine learning, where you use 
# one subset (the training set) to train your model and another subset
# (the testing set) to evaluate its performance.

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state = 1)

In [32]:
print(x_train)

[[0.0 0.0 0.0 1.0 48.0 58000.0]
 [1.0 0.0 0.0 0.0 3.0 51000.0]
 [0.0 1.0 0.0 0.0 40.142857142857146 66000.0]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 105.0 79000.0]
 [0.0 1.0 0.0 0.0 35.0 56000.0]
 [0.0 0.0 0.0 1.0 40.142857142857146 51000.0]]


In [33]:
print(x_test)

[[1.0 0.0 0.0 0.0 30.0 52000.0]
 [0.0 0.0 0.0 1.0 40.142857142857146 50000.0]
 [0.0 0.0 1.0 0.0 33.0 69000.0]]


In [34]:
print(y_train)

[1 1 0 1 1 0 0]


In [35]:
print(y_test)

[0 0 0]


#### feature scaling - Standarisation & Normalization

In [2]:
from sklearn.preprocessing import StandardScaler
# Standardization is a common preprocessing technique used in machine 
# learning to scale your data in such a way that it has a mean of 0 and
# a standard deviation of 1. This helps make the features in your dataset 
# more compatible with various machine learning algorithms.


In [ ]:
scaler =StandardScaler()

In [ ]:
x_train[:,4:]= scaler.fit_transform(x_train[:,4:])

In [ ]:
x_test[:,4:]= scaler.fit_transform(x_test[:,4:])

In [ ]:
print(x_train)

##### outliers

In [ ]:
print(x_test)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
%matplotlib inline

In [ ]:
#define our dataset
our_dataset = [11,10,12,14,12,15,14,13,15,102,12,14,12,108,12,11,14,13,15,10,15,12,10,14,13,15,10]

In [ ]:
plt.hist(our_dataset)

##### Find and remove outliers

In [ ]:
plt.hist(dataset['Age'],bins=15)

In [ ]:
# Quantile Method
dataset

In [ ]:
lowerLimit = dataset['Age'].quantile(0.05) 

In [ ]:
lowerLimit

In [ ]:
dataset [dataset['Age'] < lowerLimit]

In [ ]:
upperLimit = dataset['Age'].quantile(0.95)

In [ ]:
upperLimit

In [ ]:
dataset [dataset['Age'] > upperLimit]

In [ ]:
dataset=dataset[(dataset['Age'] > lowerLimit) & (dataset['Age'] < upperLimit)]

In [ ]:
dataset

### Removing duplicate records from dataset

In [3]:
dataset.drop_duplicates()

City    Age   Salary Eligible for bonus
0     Mumbai    3.0  51000.0                Yes
1    Newyork   27.0  48000.0                Yes
2     Mumbai   30.0  52000.0                 No
3    Newyork    NaN  66000.0                 No
4      Tokyo   48.0      NaN                Yes
5      Tokyo    NaN  51000.0                 No
6  Singapore   33.0  69000.0                 No
7    Newyork  105.0  79000.0                Yes
8    Newyork   35.0  56000.0                 No
9      Tokyo    NaN  50000.0                 No

In [6]:
dataset.drop_duplicates(subset=['City'])

City   Age   Salary Eligible for bonus
0     Mumbai   3.0  51000.0                Yes
1    Newyork  27.0  48000.0                Yes
4      Tokyo  48.0      NaN                Yes
6  Singapore  33.0  69000.0                 No

In [11]:
dataset.drop_duplicates(subset=['City','Eligible for bonus'])

City   Age   Salary Eligible for bonus
0     Mumbai   3.0  51000.0                Yes
1    Newyork  27.0  48000.0                Yes
2     Mumbai  30.0  52000.0                 No
3    Newyork   NaN  66000.0                 No
4      Tokyo  48.0      NaN                Yes
5      Tokyo   NaN  51000.0                 No
6  Singapore  33.0  69000.0                 No