In [6]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Create a sample dataset
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to your data (compute mean and standard deviation)
scaler.fit(data)

# Transform your data by applying the standardization
scaled_data = scaler.transform(data)

# The scaled_data now contains the standardized values
print("Original data:")
print(data)
print("\nStandardized data:")
print(scaled_data)


Original data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Standardized data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
